spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

token:
  expiration_time: 86400000
  secret: '{cipher}AQAU+R3tq5zv197fQQjxo5Afvp2YtST+kYaSYjlutadiwTLkTe7rxZ3Tn8/olzH10iUixxMQ7HCzrPHL1F2vfNgm3WrBRk+LyfcsStLsBLi02YIWqv6nBnxM6UuOOFnreozR1hroVKrMxPSvqKuAYzegVV6f1CP+wJEEPsRY9OcLpylamojwQy8aOa+SUjkRh658kugDh+P69tN9YhssScw1mkzRRT7kRNowwZVeeCXzmG4OGsIrvwAaaAd68J6p815FNJLpmPwahz3sIYCoS+C8i+dtTwuYFp6LfMbLFkLvvbSuGYyzIExWGUMYhbcd/8A/hjDMG/0ldfYfrg0MPNCEFnH53TvTlqb0Aa+sXoPQKykSfAe3802RzefUhAVNctQhabqw73xBJQLCNaVljk1A'
gateway:
  ip: 127.0.0.1

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order-is-empty: User's order is empty.
